# PEGADAIAN Address Scrapping

# Import Libraries
### For web scrapping

the data will be taken from imdb website: https://www.pegadaian.co.id/lokasi-cabang/page/1

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from requests import get
from bs4 import BeautifulSoup as Soup
from bs4 import NavigableString, Tag

ModuleNotFoundError: No module named 'tensorflow'

## Get the site necessity

In [ ]:
url = get("https://www.pegadaian.co.id/lokasi-cabang/page/1")

In [3]:
request = url.text

### Parse the whole site

In [4]:
total_soup = Soup(request,'html.parser')

### Get the part related to the Movie profiles

In [5]:
total_movies = total_soup.findAll('div',{'class':'lister-item mode-advanced'})

### Find the number of possible pages that wee need to get all movies

#### In this case, it is 69, as the movie list has 3490 entry, and each page contains 50 movies.

In [6]:
total_movie = total_soup.find('div', {'class':'desc'}).find('span').text
page_count = total_movie[total_movie.find('of ')+3:total_movie.find(' titles')].replace(',','')
pages = int(float(page_count)/50)
print(pages)

69

In [11]:
def country_movies_imdb(country_code):
    url = get("https://www.imdb.com/search/title/?country_of_origin={}&sort=release_date,desc&start=51&ref_=adv_nxt".format(country_code))
    request = url.text
    total_soup = Soup(request,'html.parser')
    total_movies = total_soup.findAll('div',{'class':'lister-item mode-advanced'})
    total_movie = total_soup.find('div', {'class':'desc'}).find('span').text
    page_count = total_movie[total_movie.find('of ')+3:total_movie.find(' titles')].replace(',','')
    pages = int(float(page_count)/50)
    
    Title = []
    Year = []
    Synopsis = []
    Runtime = []
    Genre = []
    Rating = []
    Actors =[]
    Director = []
    Votes = []
    
    for pag in range(pages):
        page = (pag*50)+1
        soup_data = Soup(request,'html.parser')
        movies = soup_data.findAll('div',{'class':'lister-item mode-advanced'})
        for mov in movies:
            #TITLE
            Title.append(mov.h3.a.text)

            #YEAR
            try:
                Year.append(mov.find('span',{"class": "lister-item-year text-muted unbold"}).text[1:5])
            except TypeError:
                Year.append(np.nan)
            except AttributeError:
                Year.append(np.nan)

            #SYNOPSIS
            try:
                Synopsis.append(mov.find_all('p',{"class": "text-muted"})[1].text[5:])
            except TypeError:
                Synopsis.append(np.nan)
            except AttributeError:
                Synopsis.append(np.nan)

            #RUNTIME
            try:
                Runtime.append(mov.find('span',{"class": "runtime"}).text[:-4])
            except AttributeError:
                Runtime.append(np.nan)
            except TypeError:
                Runtime.append(np.nan)

            #GENRE
            try:
                Genre.append(mov.find('span',{"class": "genre"}).text[1:-12])
            except AttributeError:
                Genre.append(np.nan)

            #RATING
            try:
                Rating.append(mov.find('div',{"class":"inline-block ratings-imdb-rating"})["data-value"])
            except AttributeError:
                Rating.append(np.nan)
            except TypeError:
                Rating.append(np.nan)

            #VOTES
            try:
                Votes.append(mov.find('span', {"name": "nv"}).text)
            except AttributeError:
                Votes.append(np.nan)
            except TypeError:
                Votes.append(np.nan)

            #ACTORS
            Actors.append([a.text for a in mov.find('p',class_='').find_all('a')[1:]])

            #DIRECTOR
            try:
                Director.append(mov.find('p',class_='').find_all('a')[0].text)
            except AttributeError:
                Director.append(np.nan)
            except IndexError:
                Director.append(np.nan)
    
    list=[Title, Year, Synopsis, Runtime, Genre, Rating, Votes, Director, Actors]
    df1 = pd.DataFrame(list).T
    df1.columns = ["Title", "Year", "Synopses", "Runtime", "Genre", "Rating", "Votes", "Director", "Actors"]
    return df1

In [ ]:
country_movies_imdb("my")

## Script below is to get List of Movies

In [7]:
Title = []
Year = []
Synopsis = []
Runtime = []
Genre = []
Rating = []
Actors =[]
Director = []
Votes = []

for pag in range(pages):
    page = (pag*50)+1
    url = "https://www.imdb.com/search/title/?country_of_origin=id&sort=release_date,desc&start={}&ref_=adv_nxt".format(page)
    request = get(url).text
    soup_data = Soup(request,'html.parser')
    movies = soup_data.findAll('div',{'class':'lister-item mode-advanced'})
    for mov in movies:
        #TITLE
        Title.append(mov.h3.a.text)

        #YEAR
        try:
            Year.append(mov.find('span',{"class": "lister-item-year text-muted unbold"}).text[1:5])
        except TypeError:
            Year.append(np.nan)
        except AttributeError:
            Year.append(np.nan)
            
        #SYNOPSIS
        try:
            Synopsis.append(mov.find_all('p',{"class": "text-muted"})[1].text[5:])
        except TypeError:
            Synopsis.append(np.nan)
        except AttributeError:
            Synopsis.append(np.nan)

        #RUNTIME
        try:
            Runtime.append(mov.find('span',{"class": "runtime"}).text[:-4])
        except AttributeError:
            Runtime.append(np.nan)
        except TypeError:
            Runtime.append(np.nan)

        #GENRE
        try:
            Genre.append(mov.find('span',{"class": "genre"}).text[1:-12])
        except AttributeError:
            Genre.append(np.nan)
            
        #RATING
        try:
            Rating.append(mov.find('div',{"class":"inline-block ratings-imdb-rating"})["data-value"])
        except AttributeError:
            Rating.append(np.nan)
        except TypeError:
            Rating.append(np.nan)

        #VOTES
        try:
            Votes.append(mov.find('span', {"name": "nv"}).text)
        except AttributeError:
            Votes.append(np.nan)
        except TypeError:
            Votes.append(np.nan)

        #ACTORS
        Actors.append([a.text for a in mov.find('p',class_='').find_all('a')[1:]])

        #DIRECTOR
        try:
            Director.append(mov.find('p',class_='').find_all('a')[0].text)
        except AttributeError:
            Director.append(np.nan)
        except IndexError:
            Director.append(np.nan)
#         print(i)

In [8]:
list=[Title, Year, Synopsis, Runtime, Genre, Rating, Votes, Director, Actors]
df = pd.DataFrame(list).T
df.columns = ["Title", "Year", "Synopses", "Runtime", "Genre", "Rating", "Votes", "Director", "Actors"]
print(df.shape)

(3450, 9)

In [55]:
df_id = df.dropna(axis = 0).reset_index(drop=True)
df_id

,Title,Year,Synopses,Runtime,Genre,Rating,Votes,Director,Actors
0,Asih 2,2020,"Terror Asih, the ghost of a poor woman who had...",104,Horror,8.4,14,Rizal Mantovani,"[Shareefa Daanish, Marsha Timothy, Ario Bayu, ..."
1,Generasi 90an: Melankolia,2020,Abby never thought he would have to lose this ...,91,Drama,7.3,6,Mohammad Irfan Ramly,"[Ari Irham, Aghniny Haque, Taskya Namya, Jenni..."
2,Quarantine Tales,2020,Quarantine Tales is a collection of stories by...,87,"Drama, Thriller",7.6,7,Ifa Isfansyah,"[Jason Iskandar, Dian Sastrowardoyo, Tata Sidh..."
3,Kemarin,2020,Film Based on the 2018 Banten Tsunami and a 55...,93,"Documentary, Drama",9.2,8,Upie Guava,"[Riefian Fajarsyah, Herman Sikumbang, M. Awal ..."
4,100% Halal,2020,"When she was just learning to cultivate love, ...",100,Drama,9,11,Jastis Arimba,"[Anisa Rahma, Anandito Dwis, Kinaryosih, Arafa..."
...,...,...,...,...,...,...,...,...,...
1280,Tamu Agung,1955,An impending visit from a VIP causes chaos and...,107,"Comedy, Drama",5,6,Usmar Ismail,"[Cassin Abbas, Nina Amora, M. Pandji Anom, Chi..."
1281,Lewat Djam Malam,1954,A hero of revolution returns to civilian life ...,101,Drama,7.1,129,Usmar Ismail,"[A.N. Alcaff, Dhalia, Netty Herawati, Bambang ..."
1282,Harimau Tjampa,1953,"Set in the 1930s, and narrated like a ballad f...",97,Drama,6.3,31,D. Djajakusuma,"[Wahid Chan, Bambang Hermanto, R.D. Ismail, Ma..."
1283,Enam Djam di Djogja,1951,Depicting the celebrated recapture of the town...,116,Drama,6.2,9,Usmar Ismail,"[R.D. Ismail, Del Juzar, Aedy Moward, Agus Mul..."
1284,Darah dan Doa,1950,It tells the story of an Indonesian revolution...,150,Drama,6.6,26,Usmar Ismail,"[Ella Bergen, Faridah, R.D. Ismail, Del Juzar]"

#### It is seems like that the movie with NaN values are either unreleased, short movies or just announced so the information is not complete. So It is better to make a new dataframe without any NaN value

#### This data will be used to train the model, as well as validating

# One hot encoding

In [56]:
for i in range(len(df_id)):
    df_id.loc[i,"Actors"] = ','.join(df_id.loc[i,"Actors"]).replace(" ","-").replace(",", " ")

In [57]:
df_id

,Title,Year,Synopses,Runtime,Genre,Rating,Votes,Director,Actors
0,Asih 2,2020,"Terror Asih, the ghost of a poor woman who had...",104,Horror,8.4,14,Rizal Mantovani,Shareefa-Daanish Marsha-Timothy Ario-Bayu Anan...
1,Generasi 90an: Melankolia,2020,Abby never thought he would have to lose this ...,91,Drama,7.3,6,Mohammad Irfan Ramly,Ari-Irham Aghniny-Haque Taskya-Namya Jennifer-...
2,Quarantine Tales,2020,Quarantine Tales is a collection of stories by...,87,"Drama, Thriller",7.6,7,Ifa Isfansyah,Jason-Iskandar Dian-Sastrowardoyo Tata-Sidhart...
3,Kemarin,2020,Film Based on the 2018 Banten Tsunami and a 55...,93,"Documentary, Drama",9.2,8,Upie Guava,Riefian-Fajarsyah Herman-Sikumbang M.-Awal-Pur...
4,100% Halal,2020,"When she was just learning to cultivate love, ...",100,Drama,9,11,Jastis Arimba,Anisa-Rahma Anandito-Dwis Kinaryosih Arafah-Ri...
...,...,...,...,...,...,...,...,...,...
1280,Tamu Agung,1955,An impending visit from a VIP causes chaos and...,107,"Comedy, Drama",5,6,Usmar Ismail,Cassin-Abbas Nina-Amora M.-Pandji-Anom Chitra-...
1281,Lewat Djam Malam,1954,A hero of revolution returns to civilian life ...,101,Drama,7.1,129,Usmar Ismail,A.N.-Alcaff Dhalia Netty-Herawati Bambang-Herm...
1282,Harimau Tjampa,1953,"Set in the 1930s, and narrated like a ballad f...",97,Drama,6.3,31,D. Djajakusuma,Wahid-Chan Bambang-Hermanto R.D.-Ismail Malin-...
1283,Enam Djam di Djogja,1951,Depicting the celebrated recapture of the town...,116,Drama,6.2,9,Usmar Ismail,R.D.-Ismail Del-Juzar Aedy-Moward Agus-Muljono
1284,Darah dan Doa,1950,It tells the story of an Indonesian revolution...,150,Drama,6.6,26,Usmar Ismail,Ella-Bergen Faridah R.D.-Ismail Del-Juzar

In [51]:
df_id["Genre"].value_counts()

Drama                         244
Horror                        168
Drama, Romance                101
Comedy                         83
Comedy, Drama                  76
                             ...
Short, Comedy, Horror           1
Short, Adventure, Fantasy       1
Fantasy, Horror, Mystery        1
Action, Biography, History      1
Action, Drama, Sport            1
Name: Genre, Length: 170, dtype: int64

In [53]:
dummies = df_id['Genre'].str.get_dummies(sep=', ')
df_id = pd.concat([df_id, dummies], axis = 1)

In [54]:
df_id

,Title,Year,Synopses,Runtime,Genre,Rating,Votes,Director,Actors,Action,...,Mystery,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western
0,Asih 2,2020,"Terror Asih, the ghost of a poor woman who had...",104,Horror,8.4,14,Rizal Mantovani,Shareefa-Daanish Marsha-Timothy Ario-Bayu Anan...,0,...,0,0,0,0,0,0,0,0,0,0
1,Generasi 90an: Melankolia,2020,Abby never thought he would have to lose this ...,91,Drama,7.3,6,Mohammad Irfan Ramly,Ari-Irham Aghniny-Haque Taskya-Namya Jennifer-...,0,...,0,0,0,0,0,0,0,0,0,0
2,Quarantine Tales,2020,Quarantine Tales is a collection of stories by...,87,"Drama, Thriller",7.6,7,Ifa Isfansyah,Jason-Iskandar Dian-Sastrowardoyo Tata-Sidhart...,0,...,0,0,0,0,0,0,0,1,0,0
3,Kemarin,2020,Film Based on the 2018 Banten Tsunami and a 55...,93,"Documentary, Drama",9.2,8,Upie Guava,Riefian-Fajarsyah Herman-Sikumbang M.-Awal-Pur...,0,...,0,0,0,0,0,0,0,0,0,0
4,100% Halal,2020,"When she was just learning to cultivate love, ...",100,Drama,9,11,Jastis Arimba,Anisa-Rahma Anandito-Dwis Kinaryosih Arafah-Ri...,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1280,Tamu Agung,1955,An impending visit from a VIP causes chaos and...,107,"Comedy, Drama",5,6,Usmar Ismail,Cassin-Abbas Nina-Amora M.-Pandji-Anom Chitra-...,0,...,0,0,0,0,0,0,0,0,0,0
1281,Lewat Djam Malam,1954,A hero of revolution returns to civilian life ...,101,Drama,7.1,129,Usmar Ismail,A.N.-Alcaff Dhalia Netty-Herawati Bambang-Herm...,0,...,0,0,0,0,0,0,0,0,0,0
1282,Harimau Tjampa,1953,"Set in the 1930s, and narrated like a ballad f...",97,Drama,6.3,31,D. Djajakusuma,Wahid-Chan Bambang-Hermanto R.D.-Ismail Malin-...,0,...,0,0,0,0,0,0,0,0,0,0
1283,Enam Djam di Djogja,1951,Depicting the celebrated recapture of the town...,116,Drama,6.2,9,Usmar Ismail,R.D.-Ismail Del-Juzar Aedy-Moward Agus-Muljono,0,...,0,0,0,0,0,0,0,0,0,0
1284,Darah dan Doa,1950,It tells the story of an Indonesian revolution...,150,Drama,6.6,26,Usmar Ismail,Ella-Bergen Faridah R.D.-Ismail Del-Juzar,0,...,0,0,0,0,0,0,0,0,0,0